using ClinicSystem.ServicesAbstration.Contracts.Services;
using ClinicSystem.Shared.DataTransferObject.PrescriptionDTOS;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace ClinicSystem.Services.Services
{
    public class PrescriptionPdfService : IPrescriptionPdfService
    {
        public PrescriptionPdfService()
        {
            QuestPDF.Settings.License = LicenseType.Community;
        }

        public Task<byte[]> GeneratePrescriptionPdfAsync(PrescriptionDTO prescription)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header()
                        .AlignCenter()
                        .Text("Clinic Prescription")
                        .FontSize(20)
                        .Bold()
                        .Underline();

                    page.Content()
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(column =>
                        {
                            column.Item().Row(row =>
                            {
                                row.RelativeItem().Text($"Doctor: {prescription.DoctorName}");
                                row.RelativeItem().Text($"Date: {prescription.PrescriptionDate:yyyy-MM-dd}");
                            });

                            column.Item().Row(row =>
                            {
                                row.RelativeItem().Text($"Patient: {prescription.PatientName}");
                            });

                            column.Item().PaddingVertical(10).LineHorizontal(1);

                            column.Item().Text("Diagnosis:").Bold();
                            column.Item().Text(prescription.Diagnosis);

                            column.Item().PaddingVertical(10).Text("Medicines:").Bold();

                            column.Item().Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.RelativeColumn(3);
                                    columns.RelativeColumn(2);
                                    columns.RelativeColumn(2);
                                    columns.RelativeColumn(2);
                                    columns.RelativeColumn(2);
                                });

                                table.Header(header =>
                                {
                                    header.Cell().Text("Medicine").Bold();
                                    header.Cell().Text("Dosage").Bold();
                                    header.Cell().Text("Frequency").Bold();
                                    header.Cell().Text("Duration").Bold();
                                    header.Cell().Text("Quantity").Bold();
                                });

                                foreach (var medicine in prescription.Medicines)
                                {
                                    table.Cell().Text(medicine.MedicineName ?? "N/A");
                                    table.Cell().Text(medicine.Dosage ?? "N/A");
                                    table.Cell().Text(medicine.Frequency ?? "N/A");
                                    table.Cell().Text($"{medicine.DurationDays} days");
                                    table.Cell().Text(medicine.Quantity.ToString());
                                }
                            });

                            if (!string.IsNullOrEmpty(prescription.Notes))
                            {
                                column.Item().PaddingTop(10).Text("Notes:").Bold();
                                column.Item().Text(prescription.Notes);
                            }
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Generated by Clinic System").FontSize(10);
                            text.Span(" - ").FontSize(10);
                            text.Span(DateTime.Now.ToString("yyyy-MM-dd HH:mm")).FontSize(10);
                        });
                });
            });

            return Task.FromResult(document.GeneratePdf());
        }
    }
}